### PR TITLE
Hash at compile time rather than doing it manually with a tool

### PR DESCRIPTION
**Pull request by TorutheRedFox**
now to add automatic texture name hashing to the tpk tool ;P

### CODE REVIEW

**Comment by xan1242** [comment]
OK, looks good! Accepting this one, thank you!

I'll try and figure out how to make a macro based version later!

**Comment by xan1242** [comment]
This change broke button maps, I'll revert some changes you've made.

**Comment by xan1242** [comment]
This PR has been reverted completely as it does not work.

**Comment by TorutheRedFox** [comment]
odd, it works without a problem on my end

what game did you test it with?

**Comment by xan1242** [comment]
Go to https://github.com/xan1242/NFS-XtendedInput/issues/23

**Pull request merged**
